ignoredOptionalDependencies:
  - global-agent
minimumReleaseAge: 720

autoInstallPeers: false

overrides:
  "@electron/get": "^4"
  "node-abi": "^4"
  "yauzl": "3.3.1"

allowBuilds:
  electron: true
  esbuild: true
  nodegit: true
  nodegit@https://codeload.github.com/weedz/nodegit/tar.gz/ead4505cf4169c0b37dd09f089d0128724249b57: true
