name: Build/release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop' || startsWith(github.ref, 'refs/tags/v')
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-10.15, windows-2016]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@master

      - name: Install linux dependencies
        if: runner.os == 'Linux'
        run: sudo apt update && sudo apt install libssh-dev libkrb5-dev

      - name: Install windows dependencies
        if: runner.os == 'Windows'
        run: vcpkg install openssl

      # - name: Install macos dependencies
      #   if: runner.os == 'macOS'
      #   run: brew install openssl

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@master
        with:
          node-version: 14
      - name: Install node dependencies
        run: npm ci --ignore-scripts
      - name: Build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run build && npm run dist
