name: Build/release

on: push

jobs:
  release:
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop' || startsWith(github.ref, 'refs/tags/v')
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # os: [macos-latest, ubuntu-latest, windows-latest]
        os: [windows-latest, macos-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install linux dependencies
        if: runner.os == 'Linux'
        run: sudo apt-get install libssh-dev libkrb5-dev

      - name: Install windows dependencies
        if: runner.os == 'Windows'
        run: vcpkg install openssl

      - name: Install macos dependencies
        if: runner.os == 'macOS'
        run: brew install openssl

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 15
      - name: Install node dependencies
        run: npm ci
      - name: Build
        run: npm run build && npm run dist

      - name: Publish
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          GH_TOKEN: ${{ secrets.github_token }}
        run: npm publish

      # - name: Build/release Electron app
      #   uses: samuelmeuli/action-electron-builder@v1
      #   with:
      #     # GitHub token, automatically provided to the action
      #     # (No need to define this secret in the repo settings)
      #     github_token: ${{ secrets.github_token }}

      #     # If the commit is tagged with a version (e.g. "v1.0.0"),
      #     # release the app after building
      #     release: ${{ startsWith(github.ref, 'refs/tags/v') }}
