name: Build/release

on:
  push:
    tags:
      - "v*"

env:
  PNPM_CACHE_FOLDER: .pnpm-store

jobs:
  release:
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop' || startsWith(github.ref, 'refs/tags/v')
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-2016]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install linux dependencies
        if: runner.os == 'Linux'
        run: sudo apt-get install libssh-dev libkrb5-dev

      - name: Install windows dependencies
        if: runner.os == 'Windows'
        run: vcpkg install openssl

      - name: Install macos dependencies
        if: runner.os == 'macOS'
        run: brew install openssl

      - name: install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 6

      - name: setup pnpm config
        run: pnpm config set store-dir $PNPM_CACHE_FOLDER

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v2
        with:
          node-version: 15

      - name: Install node dependencies
        run: pnpm i --ignore-scripts
      - name: Build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpm run build && pnpm run dist
