name: Test
on: push
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v5

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        id: pnpm-install
        with:
          run_install: false

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "pnpm"

      - name: Install node dependencies
        # Skip install scripts, otherwise we build nodegit on `npm install`.
        run: |
          pnpm install --ignore-scripts --frozen-lockfile
          # cd node_modules/nodegit && pnpm install && node generate

      - name: Run lint
        run: pnpm run format:check && pnpm run lint
