name: Test
on: push
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 6
      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'pnpm'
      - name: Install node dependencies
# Skip install scripts, otherwise we build nodegit on `npm install`.
        run: pnpm install --frozen-lockfile --ignore-scripts
      - name: Run ESLint
        run: pnpm run lint
